C
      FUNCTION DFNCII(B1)
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      DIMENSION BLOWC(2),BUPC(2)
      EXTERNAL DFNC00
      COMMON /HSD01L/ BLOWC,BUPC,ARG1,ACCREQ,INCCC
      ARG1=B1
      DFNCII=GAUSK2(DFNC00,BLOWC(1),BUPC(1),ACCREQ)
      END
