C
      FUNCTION DFNC00(B2)
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      DIMENSION ARG(2),BLOWC(2),BUPC(2)
      COMMON /HSD01L/ BLOWC,BUPC,ARG1,ACCREQ,INCCC
      NDIM=2
      ARG(1)=ARG1
      ARG(2)=B2
      IF (INCCC.EQ.1) THEN
        DFNC00=HSNCG1(NDIM,ARG)
      ELSEIF (INCCC.EQ.2) THEN
        DFNC00=HSCCG1(NDIM,ARG)
      ENDIF
      END
