CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     HSBCGA: FORM FACTOR FOR GAMMA-GAMMA-BOX DIAGRAMS
C     IR-FINITE PART ONLY
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      FUNCTION HSBCGA(T,S)
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMPLEX*16 HSBCGA,HSCLN,EPS
      COMMON /HSKNST/ PI,ALPHA,ALP1PI,ALP2PI,ALP4PI,E,GF,SXNORM,SX1NRM
      EPS=DCMPLX(0D0,1D-9)
      EPS=HSCLN(S/(T+EPS) )
      HSBCGA=T/2./(T+S)*EPS - T*(T+2.*S)/4./(T+S)/(T+S)*(EPS*EPS+PI*PI)
      END
