CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      FUNCTION HSBXCA (RG,RH,CM)
      COMPLEX*16 HSBXCA,CM,G,H,HSSPEN,HSCLN,IEPS
      DOUBLE PRECISION RG,RH
      H=DCMPLX(RH,0D0)
      G=DCMPLX(RG,0D0)
      IEPS=DCMPLX(0D0,1D-8)
      HSBXCA =(G-CM)/(G+H)*(HSCLN(H/(G-CM))-CM/G*HSCLN(CM/(CM-G))+
     *     (G+2D0*H+CM)/(G+H)*
     *(HSSPEN(G/CM)-HSSPEN(-H/CM)+HSCLN(-H/CM)*
     *    HSCLN((CM-G)/(CM+H))))
      END
