CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      FUNCTION HSBXCV (RG,RH,CM)
      COMPLEX*16 HSBXCV,HSBXCA,CM,G,H,HSSPEN,HSCLN,IEPS,T1,T2,T3
      DOUBLE PRECISION RG,RH
      H=DCMPLX(RH,0D0)
      G=DCMPLX(RG,0D0)
      IEPS=DCMPLX(0D0,1D-8)
      T1=HSBXCA(RG,RH,CM)
      T2=-2D0*HSCLN(-G/H-IEPS)*HSCLN(CM/(CM-G))
      T3=2D0*HSSPEN((CM+H)/H)
      HSBXCV=T1+T2+T3
      END
