C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C     SOFT BREMSSTRAHLUNG FOR ELECTRON-QUARK SCATTERING
C     NO RESTRICTION ON Q2, NO QUARKONIC AND NO INTERFERENCE PARTS
C     (SCALAR PART)
C
      FUNCTION HSDQDS(X,Q2)
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMPLEX*16 HSFONE
      COMMON /HSGSW1/ MEI,MEF,MQI,MQF,MEI2,MEF2,MQI2,MQF2,MPRO,MPRO2
      COMMON /HSPARL/ LPAR(20),LPARIN(12)
C
      HSDQDS=0D0
      IF (LPAR(12).EQ.1) THEN
        HSDQDS = HSDQDS + 2D0*MEI2/(Q2+4D0*MEI2)
     *          *(DREAL(HSFONE(-Q2,MEI,MEI))-2D0)
      ENDIF
      RETURN
      END
