C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
      FUNCTION HSEL22(Q2)
C
C   D2SIG*DQ2 FOR ELASTIC EP INCLUDING SOFT AND VIRTUAL CORRECTIONS
C
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMMON /HSOPTN/ INT2(5),INT3(15),ISAM2(5),ISAM3(15),
     *                IOPLOT,IPRINT,ICUT
      COMMON /HSGSW1/ MEI,MEF,MQI,MQF,MEI2,MEF2,MQI2,MQF2,MPRO,MPRO2
      COMMON /HSELAB/ SP,EELE,PELE,EPRO,PPRO
      COMMON /HSKPXY/ XX,Y
      COMMON /HSUNTS/ LUNTES,LUNDAT,LUNIN,LUNOUT,LUNRND
      COMMON /HSPARM/ POLARI,LLEPT,LQUA
C      DATA NEVERR /0/
C      LOGICAL LERR
C      DATA LERR /.TRUE./
C
      GSP=SP-MEI2-MPRO2
      XX=1D0
      Y=Q2/GSP
      IF(IPRINT.GT.20)
     &  WRITE(LUNTES,'(A/2(1PD13.5),F8.3,2I3)')
     *         ' HSEL22: SP, Q2, POLARI,LLEPT,LQUA',
     *         SP,Q2,POLARI,LLEPT,LQUA
      HSEL22=HSSGEL(Q2,LLEPT,POLARI,LQUA)/SP
C
C     IF(HSEL22.LT.0D0) THEN
C       NEVERR=NEVERR+1
C       IF (NEVERR.LT.20) THEN
C        WRITE(LUNTES,'(A,/,2(1PD13.5),2I3,F8.3)')
C    +     ' HSEL22: Q2, HSEL22, LLEPT, LQUA, POLARI',
C    +      Q2, HSEL22, LLEPT, LQUA, POLARI
C       ELSEIF (LERR) THEN
C        LERR=.FALSE.
C        WRITE(LUNTES,'(A,I3,A)')
C    &     ' ERROR HSEL22 < 0 HAS OCCURED ',NEVERR,
C    &     ' TIMES, NO FURTHER WARNINGS ARE PRINTED'
C       ELSE
C       ENDIF
C       HSEL22=0D0
C     ENDIF
      RETURN
      END
