C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
      FUNCTION HSENUW(T)
C---IR-FINITE PART
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMPLEX*16 HSENUW,HSCLM2,HSCLM4,HSCLN,CMW2,CMZ2
      COMMON /HSPARL/ LPAR(20),LPARIN(12)
      COMMON /HSKNST/ PI,ALPHA,ALP1PI,ALP2PI,ALP4PI,E,GF,SXNORM,SX1NRM
      COMMON /HSGSW/  SW,CW,SW2,CW2
     *              ,MW,MZ,MH,ME,MMY,MTAU,MU,MD,MS,MC,MB,MT
     *              ,MW2,MZ2,MH2,ME2,MMY2,MTAU2,MU2,MD2,MS2,MC2,MB2,MT2
      COMMON /HSCBMS/ CMW2,CMZ2
      HSENUW=DCMPLX(0D0,0D0)
      IF (LPAR(12).GT.0) THEN
      HSENUW=HSENUW+ALP4PI*(HSCLN(ME2/CMW2)
     1                     +3D0*HSCLM4(T,CMW2,(0D0,0D0),ME2))
      ENDIF
      IF (LPAR(15).EQ.1) THEN
      HSENUW=HSENUW+ALP4PI*(3D0*(3D0*CW2-1D0)/2D0/SW2
     1           +((2D0*SW2-1D0)/2D0/SW2+3D0*CW2/SW2/SW2)*DLOG(CW2)
     2           +(2D0*SW2-1D0)/4D0/SW2/CW2*HSCLM2(T,CMZ2)
     3           +3D0*CW2/SW2*HSCLM4(T,CMW2,CMZ2,0D0))
      ENDIF
      RETURN
      END
