        FUNCTION HSSIGN(X,Y)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       HSSIGN(X,Y)=|X|*SGN(Y) IM GEGENSATZ ZUR INTRINSIC FUNCTION
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DOUBLE PRECISION HSSIGN,X,Y
        IF (Y)  10,20,30
10      HSSIGN=-DABS(X)
        RETURN
20      HSSIGN=0D0
        RETURN
30      HSSIGN=DABS(X)
        RETURN
        END
