CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
      FUNCTION HSSRZZ(Q2)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       HSSRZZ(Q2): BEITRAEGE ZUR Z-BOSONSELBSTENERGIE (RENORMIERT)
C              Q2 = Q**2 VIEREIMPULSQUADRAT
C-----------------------------------------------------------------------
C       21.10.83
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMPLEX*16 CJFINZ,CAFINZ,CAFINW
     *          ,HSSRZZ,HSSFZZ,HSSFWW
      COMMON /HSKNST/ PI,ALPHA,ALP1PI,ALP2PI,ALP4PI,E,GF,SXNORM,SX1NRM
      COMMON /HSGSW/  SW,CW,SW2,CW2
     *              ,MW,MZ,MH,ME,MMY,MTAU,MU,MD,MS,MC,MB,MT
     *              ,MW2,MZ2,MH2,ME2,MMY2,MTAU2,MU2,MD2,MS2,MC2,MB2,MT2
      COMMON /HSPARL/ LPAR(20),LPARIN(12)
        SQ=ALP4PI*(DLOG(MU2/MD2)+DLOG(MC2/MS2)+DLOG(MT2/MB2))
        SP=ALP4PI*DLOG(MT2/MB2)*(MT2-MB2)/4./SW2/MW2
        CAFINZ=HSSFZZ(MZ2)
        CAFINW=HSSFWW(MW2)
        RDMZ2=DREAL(CAFINZ)
        RDMW2=DREAL(CAFINW)
        MRENK0=(CW2/SW2-1D0)*(RDMZ2/MZ2 - RDMW2/MW2) + ALP2PI/3D0
     *         + SQ/3./SW2 + SP*(CW2/SW2-1D0)
        CJFINZ=DCMPLX(RDMZ2,0D0)
        HSSRZZ=(HSSFZZ(Q2)-CJFINZ+(Q2-MZ2)*MRENK0)
        IF (LPAR(7).EQ.2) THEN
          DDALPP=HSDSGQ(MZ2)*(Q2-MZ2)
          HSSRZZ=HSSRZZ+DCMPLX(DDALPP,0D0)
        ENDIF
      RETURN
      END
