CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C
      FUNCTION HSSRGZ(Q2)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       HSSRGZ(Q2): BEITRAEGE ZUR GAMMA-Z-MISCHUNG (RENORMIERT)
C              Q2 = Q**2 VIEREIMPULSQUADRAT
C-----------------------------------------------------------------------
C       21.10.83
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMPLEX*16 HSSRGZ,HSSFGZ,HSSFZZ,HSSFWW,CAFINW,CAFINZ
      COMMON /HSKNST/ PI,ALPHA,ALP1PI,ALP2PI,ALP4PI,E,GF,SXNORM,SX1NRM
      COMMON /HSGSW/  SW,CW,SW2,CW2
     *              ,MW,MZ,MH,ME,MMY,MTAU,MU,MD,MS,MC,MB,MT
     *              ,MW2,MZ2,MH2,ME2,MMY2,MTAU2,MU2,MD2,MS2,MC2,MB2,MT2
        SQ=ALP4PI*(DLOG(MU2/MD2)+DLOG(MC2/MS2)+DLOG(MT2/MB2))
        SP=ALP4PI*DLOG(MT2/MB2)*(MT2-MB2)/4./SW2/MW2
        CAFINZ=HSSFZZ(MZ2)
        CAFINW=HSSFWW(MW2)
        RDMZ2=DREAL(CAFINZ)
        RDMW2=DREAL(CAFINW)
        MRENK1=CW/SW*(RDMZ2/MZ2 - RDMW2/MW2) +SQ/6./SW/CW + SP*CW/SW
        HSSRGZ=-(HSSFGZ(Q2)+ Q2 *MRENK1)
      RETURN
      END
