C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
      FUNCTION HSWG2L(GS,GT,CM2)
      IMPLICIT DOUBLE PRECISION (A-H,M,O-Z)
      COMPLEX*16 HSWG2L,CM2,HSCWLL,HSCWQL,HSCIR
      COMMON /HSKNST/ PI,ALPHA,ALP1PI,ALP2PI,ALP4PI,E,GF,SXNORM,SX1NRM
      COMMON /HSGSW/  SW,CW,SW2,CW2
     *              ,MW,MZ,MH,ME,MMY,MTAU,MU,MD,MS,MC,MB,MT
     *              ,MW2,MZ2,MH2,ME2,MMY2,MTAU2,MU2,MD2,MS2,MC2,MB2,MT2
      HSWG2L=-CM2/2D0*(HSCWLL(GS,CM2)+HSCWQL(GS,CM2,MD2))
     *       -GT/2D0*HSCIR(GT,MD2)
      HSWG2L=HSWG2L*ALP2PI
      END
