name: build
on:
 push:
 pull_request:
 schedule:
#Every 5 days at midnight 
    - cron:  "0 0 1/15 * *"

jobs:


  compilejobCentOS7:
    runs-on: ubuntu-latest
    name: Rapgap_on_CentOS7
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/centos7
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

